name: plugin_system
description: 插件系统核心模块
version: 1.0.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  # Flutter框架
  flutter:
    sdk: flutter

  # 数据序列化
  freezed_annotation: ^2.4.4
  json_annotation: ^4.8.1

  # 网络请求
  dio: ^5.4.0

  # 工具库
  equatable: ^2.0.5
  intl: ^0.19.0
  meta: ^1.16.0
  uuid: ^4.5.1


dev_dependencies:
  # 代码生成
  build_runner: ^2.4.7
  freezed: ^2.5.7
  json_serializable: ^6.9.0

  # 测试
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  test: ^1.24.0

  # 代码质量
  lints: ^3.0.0
  very_good_analysis: ^6.0.0

